from pydantic import BaseModel, Field, field_validator, model_validator
import json
from pathlib import Path
import scanpy as sc
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import pandas as pd
import numpy as np
import re
from . import logger

OTHER_LABEL = "other"

class ColorByConfig(BaseModel):
    """
    Model for the label_key config in the plot config. This will hold the meta_variable to color by and the target 
    categories to assign individual colors.
    """
    meta_key: str
    categories: list[str] = Field(default_factory=list)
    color_map: dict[str, str] = Field(default_factory=dict)
    
    @field_validator("color_map")
    @classmethod
    def color_map_values_are_hex(cls, v: dict[str, str]) -> dict[str, str]:
        # Make sure that all values in the color_map are valid 6 character hex color strings.
        # This was generated by Copilot using the prompt: "Make sure that all values in the color_map are valid 6 character hex color strings"
        hex_color_pattern = r"^#[0-9A-Fa-f]{6}$"
        for color in v.values():
            if not isinstance(color, str) or not re.match(hex_color_pattern, color):
                raise ValueError(f"Color map value {color} is not a valid hex color string.")
        return v


class PlotConfig(BaseModel):
    """
    Top level model for the plot config JSON.
    Attributes:
        src_adata_path (str): Path to the source scanpy AnnData .h5ad file.
        plot_title (str): Title for the UMAP plot.
        custom_metadata (Path | None): Optional path to a TSV file containing extra metadata to merge into the AnnData object.
        color_by (ColorByConfig): Configuration for coloring the UMAP plot points.
    """
    src_adata_path: str
    plot_title: str
    out_dir_name: str
    custom_metadata: Path | None = None
    color_by: ColorByConfig

    @field_validator("src_adata_path")
    @classmethod
    def src_adata_path_must_exist(cls, v: str) -> str:
        # Make sure that the src_adata_path exists
        path = Path(v)
        if not path.exists():
            raise ValueError(f"src_adata_path {v} does not exist")
        return v

    @field_validator("src_adata_path")
    @classmethod
    def src_adata_path_must_be_h5ad(cls, v: str) -> str:
        # Make sure that the src_adata_path ends with .h5ad
        if not v.endswith(".h5ad"):
            raise ValueError("src_adata_path must be a path to a .h5ad file")
        return v
    
    @field_validator("out_dir_name")
    @classmethod
    def directory_name_safe(cls, v: str) -> str:
        # Make sure that the out_dir_name is directory name safe. Precaution to make sure that no funny business happens with directory names.
        if not re.match(r"^[\w\-.]+$", v):
            raise ValueError(
                "out_dir_name must be directory name safe (alphanumeric, dash, underscore, dot)"
            )
        return v

    @field_validator("custom_metadata")
    @classmethod
    def custom_metadata_must_exist(cls, v: Path) -> Path:
        # If custom_metadata is provided, make sure that the path exists
        if v is not None and not v.exists():
            raise ValueError(f"custom_metadata path {v} does not exist")
        return v
    
    @field_validator("custom_metadata")
    @classmethod
    def custom_metadata_field_correct_file_type(cls, v: Path) -> Path:
        # If custom_metadata is provided, make sure that the file is a .tsv
        if v is not None and not str(v).endswith(".tsv"):
            raise ValueError("custom_metadata must be a path to a .tsv file")
        return v


def load_plot_config(file_path: Path) -> PlotConfig:
    """
    Load a json config file and parse it into a PlotConfig object.
    """
    # Check that the file path exists
    if not file_path.exists():
        raise FileNotFoundError(f"Config file {file_path} does not exist.")
    
    # Read the file content
    with file_path.open("r") as f:
        config_data = json.load(f)
    
    return PlotConfig.model_validate(config_data)

def load_scanpy_adata(file_path: Path):
    """
    Load a AnnData object from the given file path.
    """
    logger.info(f"Loading AnnData object from {file_path}.")
    adata = sc.read_h5ad(file_path)
    return adata

def load_extra_metadata(file_path: Path) -> pd.DataFrame:
    """
    Load extra metadata from a TSV file into a pandas DataFrame.
    Assumes the first column is the index (e.g., sample IDs).
    """
    metadata_df = pd.read_csv(file_path, sep="\t", index_col=0)
    return metadata_df

def validate_extra_metadata(adata: sc.AnnData, metadata_df: pd.DataFrame) -> bool:
    """
    Validate that the indices of the metadata DataFrame exist in the AnnData object's obs dataframe.
    """
    missing_ids = [idx for idx in metadata_df.index if idx not in adata.obs.index]
    if missing_ids:
        raise ValueError(f"The following IDs from the extra metadata are missing in the AnnData obs: {missing_ids}")
    return True

def merge_extra_metadata(adata: sc.AnnData, metadata_df: pd.DataFrame) -> None:
    """
    Merge extra metadata from the given DataFrame into the AnnData object's obs dataframe.
    The DataFrame's index should match the AnnData obs index.
    """
    adata.obs = adata.obs.join(metadata_df, how="left")

def validate_color_by(adata: sc.AnnData, label_key_config: ColorByConfig) -> bool:
    """
    Validate that the given meta_variable exists in the AnnData object's obs dataframe.
    """
    if label_key_config.meta_key not in adata.obs.columns:
        raise ValueError(f"meta_variable {label_key_config.meta_key} does not exist in the AnnData object's obs dataframe.")
    
    # Ensure that the targeted categories exist in the meta_variable column
    if label_key_config.categories:
        existing_categories = adata.obs[label_key_config.meta_key].unique().tolist()
        for category in label_key_config.categories:
            if category not in existing_categories:
                raise ValueError(f"target_category {category} does not exist in the meta_variable {label_key_config.meta_key}.")
    return True

def correct_base_colormap(color_map: dict[str, str], legend_labels: list[str]) -> dict:
    """
    Correct a color map so that only keys that exist in legend_labels are kept.
    """
    corrected_map = {}
    for color_map_label in color_map:
        if color_map_label in legend_labels:
            corrected_map[color_map_label] = color_map[color_map_label]
        else:
            logger.warning(f"Color map label {color_map_label} not found in legend labels; skipping.")

    return corrected_map

def legend_to_meta_values(adata: sc.AnnData, color_by: ColorByConfig, other_label: str = OTHER_LABEL,) -> dict:
    """
    Group observed metadata values into display (legend) categories.

    Given an AnnData and a `ColorByConfig`, produce a mapping where keys are
    the display/legend labels and values are lists of the raw observed
    metadata values that should be shown under that legend label.

    Behavior:
    - If an observed value is present in `color_by.categories`, it is placed
      under its own display label (the same string).
    - Otherwise the observed value is placed under `other_label`.
    - If `color_by.categories` is empty, all observed values map to themselves.

    Args:
        adata: AnnData containing the column to color by in `adata.obs`.
        color_by: ColorByConfig containing `meta_key` and `categories`.
        other_label: Label used for all values not explicitly listed in
            `color_by.categories`.

    Returns:
        dict: {display_label: [metadata_value1, metadata_value2, ...]}
    """
    col = color_by.meta_key
    # Preserve the user-provided category order; create empty lists for them
    legend_to_meta_values: dict = {cat: [] for cat in color_by.categories}
    category_set = set(color_by.categories)

    # If the categorys list is empty, all observed values map to themselves
    if not category_set:
        observed = pd.unique(adata.obs[col]).tolist()
        for v in observed:
            legend_to_meta_values.setdefault(v, []).append(v)
        return legend_to_meta_values

    # Iterate observed values in first-seen order and assign to buckets
    observed = pd.unique(adata.obs[col]).tolist()
    for v in observed:
        if v in category_set:
            legend_to_meta_values.setdefault(v, []).append(v)
        else:
            legend_to_meta_values.setdefault(other_label, []).append(v)

    return legend_to_meta_values

def gen_colormap(display_categories_dict: dict, base_color_map: dict[str, str] = {}, base_palette: str = "tab10") -> dict:
    """
    Generate a color map for each display (legend) category.

    Uses colors from a base color map when provided for a display label,
    and fills in any remaining labels using a seaborn palette.

    Args:
        display_categories: dict {display_label: [metadata_value, ...]}
        base_color_map: dict {display_label: hex_color_string}. Precondition: all keys exist in display_categories.
        base_palette: Name of a seaborn color palette for generating extra colors (passed to `seaborn.color_palette`).

    Returns:
        dict: Mapping display_label -> hex color string
    """
    display_categories = list(display_categories_dict.keys())
    color_map: dict[str, str] = base_color_map.copy()

    # Determine which labels still need colors
    unassigned = [d for d in display_categories if d not in color_map]
    if unassigned:
        palette = sns.color_palette(base_palette, n_colors=len(unassigned))
        for i, label in enumerate(unassigned):
            color_map[label] = mcolors.to_hex(palette[i])
    return color_map

def init_figure(plot_title: str):
    # figure size in inches
    width, height = 10, 8

    fig = plt.figure(figsize=(width, height))

    # Create a single Axes
    ax = plt.axes([0.1, 0.1, 0.8, 0.8])  # left, bottom, width, height (range 0 to 1)
    # Remove axis ticks
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_title(plot_title)
    return fig, ax

def plot_points(adata: sc.AnnData, plot_config: PlotConfig, display_categories: dict, color_map: dict, ax: plt.Axes) -> None:
    """
    Plot the UMAP points from the AnnData object on the given Axes. Points are grouped based on the display categories parameter
    and colored according to the color map.

    Args:
        adata: AnnData containing UMAP coordinates in `adata.obsm['X_umap']` and metadata in `adata.obs`.
        plot_config: PlotConfig containing the color_by configuration.
        display_categories: dict mapping display categories to lists of metadata values.
        color_map: dict mapping display categories to RGB tuple colors.
        ax: Matplotlib Axes to plot on.
    """
    # Extract coordinates and metadata as arrays for vectorized access
    coords = adata.obsm['X_umap']
    meta_values = adata.obs[plot_config.color_by.meta_key].values

    for legend_label, group_meta_values in display_categories.items():
        # Create a boolean mask for all metadata values that map to this legend label
        mask = np.isin(meta_values, group_meta_values)
        # np.isin does not do nan = nan comparison. Include those if needed.
        if any(pd.isna(v) for v in group_meta_values):
            mask = mask | pd.isna(meta_values)
        color = color_map[legend_label]
        
        # Plot the other label points behind the rest
        zorder = 0 if legend_label == OTHER_LABEL else 1

        ax.scatter(
            coords[mask, 0],
            coords[mask, 1],
            color=color,
            label=legend_label,
            alpha=1.0,
            edgecolor="none",
            s=30,  # point size
            zorder=zorder
        )

def add_legend(ax: plt.Axes) -> None:
    """
    Add a legend to the given Axes.
    """
    ax.legend(
        title="Categories",
        loc="upper left",
        bbox_to_anchor=(1.02, 1),  # Places it to the right, outside
        borderaxespad=0,
        fontsize="small",
        title_fontsize="medium",
        frameon=True,
        fancybox=False,
        framealpha=0.9,
        edgecolor="black",
    )

def plot_umap(adata: sc.AnnData, plot_config: PlotConfig) -> plt.Figure:
    logger.info(f"Starting plot for {plot_config.plot_title}.")
    # If custom metadata is provided, load and merge it into the AnnData object
    if plot_config.custom_metadata:
        logger.info(f"{plot_config.plot_title}: Adding custom metadata to AnnData object.")
        extra_metadata = load_extra_metadata(plot_config.custom_metadata)
        validate_extra_metadata(adata, extra_metadata)
        merge_extra_metadata(adata, extra_metadata)
    # Validate that the ColorByConfig is compatible with the AnnData object
    validate_color_by(adata, plot_config.color_by)
    # Map each legend label to the corresponding metadata values.
    legend_to_meta_map = legend_to_meta_values(adata, plot_config.color_by, other_label=OTHER_LABEL)
    # Validate the entries of the configuration color map against the legend labels
    corrected_color_map = correct_base_colormap(plot_config.color_by.color_map, list(legend_to_meta_map.keys()))
    # Generate a color map for the legend labels.
    color_map = gen_colormap(legend_to_meta_map, corrected_color_map)
    # Init a matplotlib figure and axes
    logger.info(f"{plot_config.plot_title}: Initializing figure.")
    fig, ax = init_figure(plot_config.plot_title)
    # Plot the UMAP points
    logger.info(f"{plot_config.plot_title}: Plotting points.")
    plot_points(adata, plot_config, legend_to_meta_map, color_map, ax)
    # Build the legend into the plot
    add_legend(ax)
    return fig


def save_figure(fig: plt.Figure, base_out_dir: Path, plot_config: PlotConfig, dpi: int = 1200) -> Path:
    """
    Save the given figure to the output file path with the specified DPI.

    Args:
        fig: Matplotlib Figure to save.
        base_out_dir: Base output directory Path.
        plot_config: PlotConfig containing the out_dir_name and plot_title.
        dpi: Dots per inch for the saved figure.

    Returns:
        Path to the saved figure file.
    """
    base_out_dir.mkdir(parents=True, exist_ok=True)
    fig_out_fp = base_out_dir / plot_config.out_dir_name / f"{plot_config.plot_title.replace(' ', '_')}.png"
    fig_out_fp.parent.mkdir(parents=True, exist_ok=True)
    logger.info(f"Saving figure to {fig_out_fp} with DPI {dpi}.")
    fig.savefig(fig_out_fp, dpi=dpi, bbox_inches='tight')
    return fig_out_fp
