[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lib_prep_tools"
version = "0.0.0"
description = "Visualization tool for comparing RNA-seq expression data across different library preparation methods using UMAP."
authors = [
    { name="Piet Rottinghuis", email="prottinghuis@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.9",
    "requests>=2.32.5",
    "scanpy>=1.11.4",
    "matplotlib>=3.10.7",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
test = [
    "pytest>=8.4.2",
    "requests-mock>=1.12.1"
]